# Generated by Django 3.2.5 on 2021-07-12 13:48

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Category')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('desc', models.TextField(verbose_name='Product Description')),
                ('prod_model', models.CharField(max_length=100, verbose_name='Product Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product Price')),
                ('stock_items', models.IntegerField(verbose_name='Product Items in Stock')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_view', cloudinary.models.CloudinaryField(max_length=255, verbose_name='front_view')),
                ('top_view', cloudinary.models.CloudinaryField(max_length=255, verbose_name='top_view')),
                ('side_view', cloudinary.models.CloudinaryField(max_length=255, verbose_name='side_view')),
                ('inner_view', cloudinary.models.CloudinaryField(max_length=255, verbose_name='inner_view')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Product Comment')),
                ('review', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Product Stars Review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product ID')),
            ],
        ),
    ]
